LogLig-Main/CmsApp/Models/ClubTeamsForm.cs
using System.Collections.Generic;
using AppModel;

namespace CmsApp.Models
{
    public class ClubTeamsForm
    {
        public int ClubId { get; set; }
        public int TeamId { get; set; }
        public int SeasonId { get; set; }
        public int CurrentSeasonId { get; set; }
        public string TeamName { get; set; }
        public bool IsNew { get; set; }
        public int SectionId { get; set; }
        public IEnumerable<Team> Teams { get; set; }
    }
}

LogLig-Main/CmsApp/Models/ClubsForm.cs
using AppModel;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace CmsApp.Models
{
    public class ClubsForm
    {
        public int? ClubId { get; set; }
        public int? SectionId { get; set; }
        public int? UnionId { get; set; }
        public int? SeasonId { get; set; }
        [Required]
        public string Name { get; set; }
        public IEnumerable<Club> Clubs { get; set; }
    }
}

LogLig-Main/CmsApp/Controllers/ClubsController.cs
using AppModel;
using CmsApp.Models;
using Omu.ValueInjecter;
using Resources;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using CmsApp.Helpers;
using System.Collections.Generic;

namespace CmsApp.Controllers
{
    public class ClubsController : AdminController
    {
        // GET: Positions
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult ListBySection(int id)
        {
            var vm = new ClubsForm { SectionId = id };
            vm.Clubs = clubsRepo.GetBySection(id);
            return PartialView("_List", vm);
        }

        public ActionResult ListByUnion(int id, int seasonId)
        {
            var vm = new ClubsForm { UnionId = id, SeasonId = seasonId };
            vm.Clubs = clubsRepo.GetByUnion(id, seasonId);
            return PartialView("_List", vm);
        }

        [HttpPost]
        public ActionResult Save(ClubsForm item)
        {
            var pos = new Club();

            if (item.ClubId.HasValue)
            {
                pos = clubsRepo.GetById(item.ClubId.Value);
                UpdateModel(pos);
            }
            else
            {
                UpdateModel(pos);
                clubsRepo.Create(pos);
            }

            clubsRepo.Save();

            return RedirectToClubList(pos);
        }

        private ActionResult RedirectToClubList(Club pos)
        {
            if (pos.SectionId.HasValue)
            {
                return RedirectToAction(nameof(ListBySection), new { id = pos.SectionId });
            }
            else
            {
                return RedirectToAction(nameof(ListByUnion), new { id = pos.UnionId, seasonId = pos.SeasonId });
            }
        }

        public ActionResult Delete(int id)
        {
            var item = clubsRepo.GetById(id);
            item.IsArchive = true;

            clubsRepo.Save();

            return RedirectToClubList(item);
        }

        [HttpPost]
        public ActionResult Update(int clubId, string name)
        {
            var club = clubsRepo.GetById(clubId);
            club.Name = name;
            clubsRepo.Save();

            TempData["SavedId"] = clubId;

            return RedirectToClubList(club);
        }

        public ActionResult Edit(int id, int? seasonId, int? sectionId, int? unionId)
        {
            var club = clubsRepo.GetById(id);

            if (club.IsArchive)
            {
                return RedirectToAction("NotFound", "Error");
            }

            if (User.IsInAnyRole(AppRole.Workers))
            {
                return RedirectToAction("Index", "NotAuthorized");
            }

            var viewModel = new EditClubViewModel()
            {
                Id = id,
                Name = club.Name,
                SectionId = club.SectionId,
                SectionName = club?.Section?.Name,
                UnionId = club.UnionId,
                UnionName = club?.Union?.Name,
                SeasonId = seasonId,
                CurrentSeasonId = seasonId ?? seasonsRepository.GetLastSeasonByCurrentClub(club).Id,
                CurrentSeasonName = seasonId.HasValue ? seasonsRepository.GetById(seasonId.Value).Name : "",
                Seasons = club.IsSectionClub ?? true ? seasonsRepository.GetClubsSeasons(id) : new List<Season>()
            };

            return View(viewModel);
        }

        public ActionResult Details(int id)
        {
            var item = clubsRepo.GetById(id);

            var vm = new ClubDetailsForm();

            vm.InjectFrom(item);
            vm.SportCenterList = db.SportCenters.OrderBy(sc => sc.Id).ToList();
            vm.Culture = getCulture();

            if (TempData["ViewData"] != null)
            {
                ViewData = (ViewDataDictionary)TempData["ViewData"];
            }

            return PartialView("_Details", vm);
        }

        [HttpPost]
        public ActionResult Details(ClubDetailsForm frm)
        {
            var maxFileSize = GlobVars.MaxFileSize * 1000;
            var savePath = Server.MapPath(GlobVars.ClubContentPath);
            var item = clubsRepo.GetById(frm.ClubId);

            UpdateModel(item);

            var imageFile = GetPostedFile("ImageFile");
            if (imageFile != null)
            {
                if (imageFile.ContentLength > maxFileSize)
                {
                    ModelState.AddModelError("ImageFile", Messages.FileSizeError);
                }
                else
                {
                    var newName = SaveFile(imageFile, "img");
                    if (newName == null)
                    {
                        ModelState.AddModelError("ImageFile", Messages.FileError);
                    }
                    else
                    {
                        if (!string.IsNullOrEmpty(item.PrimaryImage))
                            FileUtil.DeleteFile(savePath + item.PrimaryImage);

                        item.PrimaryImage = newName;
                    }
                }
            }

            var logoFile = GetPostedFile("LogoFile");
            if (logoFile != null)
            {
                if (logoFile.ContentLength > maxFileSize)
                {
                    ModelState.AddModelError("LogoFile", Messages.FileSizeError);
                }
                else
                {
                    var newName = SaveFile(logoFile, "logo");
                    if (newName == null)
                    {
                        ModelState.AddModelError("LogoFile", Messages.FileError);
                    }
                    else
                    {
                        if (!string.IsNullOrEmpty(item.Logo))
                            FileUtil.DeleteFile(savePath + item.Logo);

                        item.Logo = newName;
                    }
                }
            }

            var indexFile = GetPostedFile("IndexFile");
            if (indexFile != null)
            {
                if (indexFile.ContentLength > maxFileSize)
                {
                    ModelState.AddModelError("IndexFile", Messages.FileSizeError);
                }
                else
                {
                    var newName = SaveFile(indexFile, "img");
                    if (newName == null)
                    {
                        ModelState.AddModelError("IndexFile", Messages.FileError);
                    }
                    else
                    {
                        if (!string.IsNullOrEmpty(item.IndexImage))
                            FileUtil.DeleteFile(savePath + item.IndexImage);

                        item.IndexImage = newName;
                    }
                }
            }

            var docFile = GetPostedFile("DocFile");
            if (docFile != null)
            {
                if (docFile.ContentLength > maxFileSize)
                {
                    ModelState.AddModelError("DocFile", Messages.FileSizeError);
                }
                var isValid = SaveDocument(docFile, frm.ClubId);
                if (!isValid)
                {
                    ModelState.AddModelError("DocFile", Messages.FileError);
                }
            }

            if (ModelState.IsValid)
            {
                clubsRepo.Save();

                TempData["Saved"] = true;
            }
            else
            {
                TempData["ViewData"] = ViewData;
            }

            return RedirectToAction("Details", new { id = item.ClubId });
        }

        [NonAction]
        private bool SaveDocument(HttpPostedFileBase file, int unionId)
        {
            string ext = Path.GetExtension(file.FileName).ToLower();

            if (ext != ".pdf")
            {
                return false;
            }

            return false;
        }

        [NonAction]
        private HttpPostedFileBase GetPostedFile(string name)
        {
            if (Request.Files[name] == null)
                return null;

            if (Request.Files[name].ContentLength == 0)
                return null;

            return Request.Files[name];
        }

        public ActionResult MainTab(int id)
        {
            var item = clubsRepo.GetById(id);

            var playersCount = item.ClubTeams.Sum(x => x.Team.TeamsPlayers.Count);

            var vm = new ClubMainTabForm();

            vm.PlayersCount = playersCount;

            vm.OfficialsCount = jobsRepo.CountOfficialsInClub(id);
            if (TempData["ViewData"] != null)
            {
                ViewData = (ViewDataDictionary)TempData["ViewData"];
            }

            return PartialView("_MainTab", vm);
        }
        public ActionResult ClubTeams(int clubId, int seasonId)
        {
            if (User.IsInAnyRole(AppRole.Workers))
            {
                return RedirectToAction("Index", "NotAuthorized");
            }
            var teams = teamRepo.GetTeamsByClubSeasonId(clubId, seasonId);
            var club = clubsRepo.GetClubById(clubId);
            var model = new ClubTeamsForm
            {
                ClubId = clubId,
                Teams = teams,
                SeasonId = seasonId,
                CurrentSeasonId = seasonId,
                SectionId = club.IsSectionClub.Value ? club.SectionId.Value : club.Union.SectionId
            };
            return PartialView("_ClubTeams", model);
        }

        [HttpPost]
        public ActionResult CreateClubTeam(ClubTeamsForm model)
        {
            var team = new Team();

            if (model.IsNew)
            {
                team.Title = model.TeamName.Trim();
                teamRepo.Create(team);
            }

            else if (model.TeamId != 0 && !model.IsNew)
            {
                team = teamRepo.GetById(model.TeamId, model.SeasonId);
            }
            else
            {
                TempData["ErrExist"] = Messages.TeamNotFound;

LogLig-Main/CmsApp/Views/Clubs/Edit.cshtml
@using CmsApp.Controllers
@model EditClubViewModel


<div class="row">
    <div class="col-lg-9">
        <h3 class="sub-header">
            @{
                if (User.IsInAnyRole(AppRole.Admins, AppRole.Editors))
                {
                    if (Model.SectionId.HasValue)
                    {
            <a href="@Url.Action(nameof(SectionsController.Edit), "Sections", new { id = Model.SectionId })">@Model.SectionName</a>
                    } else
	                {
            <a href="@Url.Action(nameof(UnionsController.Edit), "Unions", new { id = Model.UnionId })">@Model.UnionName</a>
	                }
                }
                else
                {
            <span>Clubs</span>
                }
            }
            &raquo; @Model.Name
        </h3>
    </div>
    <div class="col-lg-3">
        <div class="form-group" style="margin-top: 20px">
            @if (Model.SectionId.HasValue)
                {
            @Html.DropDownListFor(m => m.CurrentSeasonId, new SelectList(Model.Seasons, "Id", "Name"), new { @class = "form-control", @id = "ddlSeasons" })
                } else
	            {
            @Html.DisplayFor(m => m.CurrentSeasonName)
	            }
        </div>
    </div>
</div>

<ul class="nav nav-tabs" id="section_tabs" role="tablist">
    <li class="active"><a href="#clubmain" data-toggle="tab">@Messages.ClubMainTab</a></li>
    <li><a href="#info" data-toggle="tab">@Messages.Info</a></li>
    <li><a href="#workers_list" data-toggle="tab">@Messages.ClubOfficialsTab</a></li>
    @if (User.IsInAnyRole(AppRole.Admins, AppRole.Editors, AppRole.Workers))
    {
        <li><a href="#auditoriums" data-toggle="tab">@Messages.Auditoriums</a></li>
    }
    <li><a href="#teams" data-toggle="tab">@Messages.Teams</a></li>
    <li><a href="#events" data-toggle="tab">@Messages.Events</a></li>
    <li><a href="#tournament" data-toggle="tab">@Messages.Tournaments</a></li>
    @if (Model.SectionId.HasValue)
    {
        <li><a href="#seasons" data-toggle="tab">@Messages.Seasons</a></li>
    }
</ul>

<div id="groupmodal" class="tab-content row offset-3">
    <div class="tab-pane active in fade col-sm-9" id="clubmain">
        @Html.Action("MainTab", new { clubId = Model.Id })
    </div>

    <div class="tab-pane fade col-sm-9" id="info">
        @Html.Action("Details")
    </div>

    <div class="tab-pane fade col-sm-7 offset-2" id="workers_list">
        @Html.Action("WorkerList", "Jobs", new { id = Model.Id, logicalName = LogicaName.Club, seasonId = Model.CurrentSeasonId })
    </div>

    <div class="tab-pane fade col-sm-7 offset-2" id="auditoriums">
        @Html.Action("List", "Auditoriums", new { clubId = Model.Id, seasonId = Model.CurrentSeasonId })
    </div>

    <div class="tab-pane fade col-sm-7 offset-2" id="teams">
        @Html.Action("ClubTeams", "Clubs", new { clubId = Model.Id, seasonId = Model.CurrentSeasonId })
    </div>

    <div class="tab-pane" fade col-sm-7 offset-2 id="events">
        @Html.Action("Index", "Events", new { clubId = Model.Id })
    </div>

    <div class="tab-pane fade col-sm-7 offset-2" id="tournament">
        @Html.Action("EilatTournament", "Unions", new { clubId = Model.Id, seasonId = Model.CurrentSeasonId })
    </div>

    <div class="tab-pane fade col-sm-7 offset-2" id="seasons">
        @Html.Action("List", "Seasons", new { entityId = Model.Id, logicalName = LogicaName.Club })
    </div>
</div>

<div class="modal fade" id="newleague" role="dialog">
    <div class="modal-dialog modal-sm">
        <div class="modal-content"></div>
    </div>
</div>

@section scripts
{
    <script>
        $('#ddlSeasons').change(function () {
            var seasonId = $(this).val();
            $.ajax({
                url: '/Admin/SetClubCurrentSeason',
                type: 'POST',
                dataType: 'JSON',
                data: { seasonId },
                success: function () {
                }
            });
            window.location.href = '@Url.Action("Edit", new { id = Model.Id })';
        });
    </script>
}

LogLig-Main/CmsApp/Views/Clubs/EditTeamClub.cshtml
@model TeamNavView
<h3 class="sub-header">
   
   @{
       if (User.IsInAnyRole(AppRole.Admins, AppRole.Editors))
       {
           <a href="@Url.Action("Edit", "Clubs", new {id = ViewBag.ClubId, sectionId = Model.SectionId})">Teams</a>
       }
       else
       {
           <span>Team</span>
       }
   }
    &raquo; @Model.TeamName
</h3>
<ul class="nav nav-tabs" id="league_tabs" role="tablist">
    <li class="active"><a href="#details" data-toggle="tab">@Messages.Info</a></li>
    @if (User.IsInAnyRole(AppRole.Admins, AppRole.Editors, AppRole.Workers))
    {
        <li><a href="#players" data-toggle="tab">@Messages.Players</a></li>
        <li><a href="#userstab" data-toggle="tab">@Messages.Workers</a></li>
        <li><a href="#halls" data-toggle="tab">@Messages.Auditoriums</a></li>
    }
    <li><a href="#schedules" data-toggle="tab">@Messages.GamesTable</a></li>
    @if (User.IsInAnyRole(AppRole.Admins, AppRole.Editors, AppRole.Workers))
    {
        <li><a href="#notifications" data-toggle="tab">@Messages.Notifications</a></li>
    }
</ul>


<div class="tab-content row offset-3">
    <div class="tab-pane fade in active col-sm-10" id="details">
        @*@Html.Action("Details", new { id = Model.TeamId, seasonId = Model.SeasonId, leagueId = Model.CurrentLeagueId })*@
    </div>
</div>

LogLig-Main/CmsApp/Views/Clubs/_ClubTeams.cshtml
@model ClubTeamsForm
@{
    string msg = "";
    if (TempData["ErrExists"] != null)
    {
        msg = TempData["ErrExists"] as string;
    }
}
<div id="club-teams-view">
    @using (Ajax.BeginForm("CreateClubTeam", null, new AjaxOptions {UpdateTargetId = "teams"}, new {id = "club-teams-form", autocomplete = "off"}))
    {
        @Html.HiddenFor(x => x.ClubId)
        @Html.HiddenFor(x => x.CurrentSeasonId)
        @Html.HiddenFor(m => m.TeamId)
        @Html.HiddenFor(x=>x.SectionId)
        <table class="table table-bordered">
            <thead>
            <tr>
                <th>#</th>
                <th>@Messages.Title</th>
                <th>&nbsp;</th>
                <th>&nbsp;</th>
            </tr>
            </thead>
            <tbody>
            @foreach (var item in Model.Teams)
            {
                <tr>
                    <td>@item.TeamId</td>
                    <td>@item.Title</td>
                    <td>
                        <a href="@Url.Action("Edit", "Teams", new {id = item.TeamId, clubId = Model.ClubId, seasonId = Model.SeasonId})" class="btn btn-primary">@Messages.Details</a>
                        @*<a class="btn btn-primary" href="@Url.Action("Edit", "Teams", new {id = m.TeamId, currentLeagueId = Model.LeagueId, seasonId = Model.SeasonId})">@Messages.Details</a>*@
                    </td>
                    <td>
                        @if (User.IsInAnyRole(AppRole.Admins, AppRole.Editors, AppRole.Workers))
                        {
                            <a href="@Url.Action("DeleteTemClub", "Clubs", new {clubId = Model.ClubId, teamId = item.TeamId, seasonId = Model.SeasonId, sectionId = Model.SectionId})" class="@AppCss.Delete"
                               data-ajax-confirm="@Messages.DeleteConfirm"
                               data-ajax-update="#teams"
                               data-ajax="true">
                            </a>
                        }
                    </td>
                </tr>
            }
            </tbody>
            <tfoot>
            @if (User.IsInAnyRole(AppRole.Admins, AppRole.Editors, AppRole.Workers))
            {
                <tr>
                    <td>
                        <div class="form-group no-marging">
                            @Html.CheckBoxFor(t => t.IsNew)
                            @Html.Label(Messages.AddNewTeam)
                        </div>
                    </td>
                    <td>
                        <div class="form-group no-marging">
                            @Html.TextBoxFor(m => m.TeamName, new
                       {
                           @class = "form-control auto-search",
                           @id = "team-auto-search",
                           placeholder = Messages.AddTeam,
                           maxlength = 50,
                           data_remote = Url.Action("FindTeam", "Search", new { sectionId = Model.SectionId})
                       })
                        </div>
                        @if (!string.IsNullOrEmpty(msg))
                        {
                            <div class="text-danger">@msg</div>
                        }
                    </td>
                    <td>
                        <button class="btn btn-primary">@Messages.Save</button>
                    </td>
                    <td></td>
                </tr>
            }
            </tfoot>
        </table>
    }
</div>
<script>
    $(document).ready(function () {
        setAutoSearch();

        $('#team-auto-search').bind('typeahead:select', function (ev, data) {
            $('[name="TeamId"]').val(data.Id);
        });

        $("#team-auto-search").keypress(function (e) {
            if (e.which != 13 || e.which != 32) {
                $('[name="TeamId"]').val(0);
            }
        });
    });
</script>

LogLig-Main/CmsApp/Views/Clubs/_List.cshtml
@model ClubsForm
@{
    int savedId = TempData["SavedId"] != null ? (int)TempData["SavedId"] : 0;
    int errId = TempData["ErrId"] != null ? (int)TempData["ErrId"] : 0;
}
<table class="table table-bordered">
    <tbody>
        @foreach (var m in Model.Clubs)
        {
            string frmid = "clubsform" + m.ClubId;
            if (User.IsInAnyRole(AppRole.Admins, AppRole.Editors))
            {
                <tr>
                    <td>
                        @m.ClubId
                    </td>
                    <td>
                        @using (Ajax.BeginForm("Update", "Clubs", new AjaxOptions { UpdateTargetId = "clubs" }, new { id = frmid }))
                        {
                            <span class="form-group">
                                <input type="text" name="Name" value="@m.Name" form="@frmid" class="form-control required" maxlength="50" />
                                @Html.ValidationMessage("Name")
                            </span>
                            <input type="hidden" name="ClubId" form="@frmid" value="@m.ClubId" />
                        }
                    </td>
                    <td>
                        <button class="@AppCss.Save @(savedId == m.ClubId ? "btn-success" : null) btn" form="@frmid"></button>
                    </td>
                    <td>
                        <a class="btn btn-primary"
                           href="@Url.Action("Edit", "Clubs",
                                new {id = m.ClubId, sectionId = m.SectionId, unionId = m.UnionId, seasonId = m.SeasonId})">
                            @Messages.Details
                        </a>
                    </td>
                    <td>
                        <a href="@Url.Action("Delete", new {id = m.ClubId})" class="@AppCss.Delete"
                           data-ajax-confirm="@Messages.DeleteConfirm"
                           data-ajax-update="#clubs"
                           data-ajax="true"></a>
                    </td>
                </tr>
            }
            else
            {
                <tr>
                    <td>
                        @m.ClubId
                    </td>
                    <td>
                        @m.Name
                    </td>
                    <td>
                        <a class="btn btn-primary"
                           href="@Url.Action("Edit", "Clubs",
                                new {id = m.ClubId, sectionId = m.SectionId, unionId = m.UnionId, seasonId = m.SeasonId})">
                            @Messages.Details
                        </a>
                    </td>
                </tr>
            }
        }
    </tbody>
    @if (User.IsInAnyRole(AppRole.Admins, AppRole.Editors))
    {
        <tfoot>
            <tr>
                <td></td>
                <td>
                    @using (Ajax.BeginForm("Save", "Clubs", new AjaxOptions { UpdateTargetId = "clubs" }, new { id = "clubsform" }))
                    {
                        <span class="form-group">
                            @Html.TextBoxFor(m => m.Name, new { @class = "form-control", placeholder = Messages.AddNew, form = "clubsform", maxlength = 50 })
                            @Html.ValidationMessageFor(m => m.Name)
                        </span>
                        @Html.HiddenFor(m => m.SectionId, new { form = "clubsform" })
                        @Html.HiddenFor(m => m.UnionId,   new { form = "clubsform" })
                        @Html.HiddenFor(m => m.SeasonId,  new { form = "clubsform" })
                    }
                </td>
                <td>
                    <button class="btn btn-primary" form="clubsform">@Messages.Save</button>
                </td>
                <td colspan="2"></td>
            </tr>
        </tfoot>
    }
</table>

<script>
    $('#clubsform').validateBootstrap(true);
</script>

LogLig-Main/CmsApp/Views/Clubs/_MainTab.cshtml
@model ClubMainTabForm
<div class="col-sm-6 form-group">
    <div class="ibox">
        <div class="ibox-content">
            <h5>סה"כ שחקנים</h5>
            <h1 class="no-margins"><span>@Model.PlayersCount</span></h1>
        </div>
    </div>
    <div class="ibox">
        <div class="ibox-content">
            <h5>סה"כ בעלי תפקידים</h5>
            <h1 class="no-margins"><span>@Model.OfficialsCount</span></h1>
        </div>
    </div>
</div>