LogLig-Main/CmsApp/Controllers/GroupsController.cs
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;

using Omu.ValueInjecter;
using AppModel;
using CmsApp.Models;
using DataService.LeagueRank;

namespace CmsApp.Controllers
{
    public class GroupsController : AdminController
    {
        // GET: Groups
        public ActionResult Index(int id, int seasonId)
        {
            var resList = stagesRepo.GetAll(id, seasonId);
            ViewBag.SeasonId = seasonId;

            return PartialView("_List", resList);
        }

        public ActionResult Delete(int id, int seasonId)
        {
            var gr = groupRepo.GetById(id);
            int leagId = gr.Stage.LeagueId;
            gr.IsArchive = true;
            groupRepo.Save();
            return RedirectToAction("Index", new { id = leagId, seasonId });
        }


        public ActionResult Create(int id, int seasonId)
        {
            var vm = new GroupsForm();
            vm.StageId = id;
            vm.NumberOfCycles = 1;
            var st = stagesRepo.GetById(id);
            vm.FirstStage = stagesRepo.CountStage(st.LeagueId) == 1;
            vm.LeagueId = st.LeagueId;
            UpdateGroupFormListsFromDB(vm);
            vm.PointId = 2;
            ViewBag.SeasonId = seasonId;
            vm.SeasonId = seasonId;
            return PartialView("_Edit", vm);
        }

        public ActionResult Edit(int id)
        {
            var vm = new GroupsForm();

            var gr = groupRepo.GetById(id);
            vm.InjectFrom(gr);
            if (gr.NumberOfCycles.HasValue)
            {
                vm.NumberOfCycles = gr.NumberOfCycles.Value;
            }
            else
            {
                vm.NumberOfCycles = 1;
            }

            vm.LeagueId = gr.Stage.LeagueId;


            UpdateGroupFormListsFromDB(vm);
            //vm.GroupsTeams = grRepo.GetTeamsGroups(vm.LeagueId);

            return PartialView("_Edit", vm);
        }

        private void UpdateGroupFormListsFromDB(GroupsForm vm)
        {
            var stageId = vm.StageId;
            var leagueTeams = teamRepo.GetTeamsByLeague(vm.LeagueId);

            var groupeTeams = groupRepo.GetTeamsGroups(vm.LeagueId)
                .Where(gt => gt.StageId == stageId)
                .OrderBy(gt => gt.Pos);

            var notIncludedTeams = leagueTeams.Where(t => !groupeTeams.Where(gt => gt.StageId == stageId)
                .Select(gt => gt.TeamId)
                .ToList()
                .Contains(t.TeamId))
                .ToList();

            var selectedTeams = new List<Team>();
            if (vm.GroupId != 0)
            {
                selectedTeams = groupRepo.GetGroupTeamsByGroupId(vm.GroupId).OrderBy(gt => gt.Pos).Select(gt => gt.Team).ToList();
            }
            vm.TeamsList = new SelectList(notIncludedTeams, "TeamId", "Title");
            vm.SelectedTeamsList = new SelectList(selectedTeams, "TeamId", "Title");
            vm.GamesTypes = new SelectList(groupRepo.GetGamesTypes(), "TypeId", "Name", vm.TypeId);
            var group = groupRepo.GetById(vm.GroupId);
            if (group != null)
                vm.PointId = group.PointEditType != null ? (int)group.PointEditType + 1 : 2;
        }

        private void UpdateGroupFormListsFromSelection(GroupsForm vm)
        {
            var notIncludedTeams = new List<Team>();
            var selectedTeams = new List<Team>();

            if (vm.TeamsArr != null)
            {
                notIncludedTeams = teamRepo.GetTeamsByIds(vm.TeamsArr);
            }


            if (vm.SelectedTeamsArr != null)
            {
                selectedTeams = teamRepo.GetTeamsByIds(vm.SelectedTeamsArr);
            }

            vm.TeamsList = new SelectList(notIncludedTeams, "TeamId", "Title");
            vm.SelectedTeamsList = new SelectList(selectedTeams, "TeamId", "Title");
            vm.GamesTypes = new SelectList(groupRepo.GetGamesTypes(), "TypeId", "Name", vm.TypeId);

            vm.GamesTypes = new SelectList(groupRepo.GetGamesTypes(), "TypeId", "Name", vm.TypeId);
        }

        [HttpPost]
        public ActionResult Edit(GroupsForm vm)
        {
            if (vm.TeamsArr != null || vm.SelectedTeamsArr != null)
            {
                UpdateGroupFormListsFromSelection(vm);
            }
            else
            {
                UpdateGroupFormListsFromDB(vm);
            }

            if (vm.SelectedTeamsArr == null || vm.SelectedTeamsArr.Count() == 0)
            {
                ModelState.AddModelError("SelectedTeamsArr", "נא להוסיף קבוצות לפני שמירה");
                return PartialView("_Edit", vm);
            }

            var item = new Group();
            if (vm.GroupId != 0)
                item = groupRepo.GetById(vm.GroupId);
            else
                groupRepo.Create(item);
            if (vm.PointId < 1 || vm.PointId > 3)
                vm.PointId = 0;

            item.PointEditType = vm.PointId - 1;
            TryUpdateModel(item);
            item.IsAdvanced = false;



            LeagueRankService svc = new LeagueRankService(vm.LeagueId);
            var teams = new List<RankTeam>();
            foreach (var team in vm.SelectedTeamsArr)
            {
                var res = svc.AddTeamIfNotExist(team, teams);
            }
            vm.Points = new int[teams.Count];
            vm.Names = new string[teams.Count];
            vm.IdTeams = new int?[teams.Count];
            for (var i = 0; i < teams.Count; i++)
            {
                vm.Points[i] = 0;
                var team = teamRepo.GetGroupTeam((int)item.GroupId, (int)teams[i].Id);
                if (team != null)
                    vm.Points[i] = team.Points!=null ? (int)team.Points:0;
                vm.Names[i] = teams[i].Title;
                vm.IdTeams[i] = teams[i].Id;
            }
            groupRepo.UpdateTeams(item, vm.SelectedTeamsArr);
            vm.InjectFrom(item);
            groupRepo.Save();
            vm.GroupId = item.GroupId;
            if (vm.PointId == 3)
            {
                TempData["GroupId"] = vm.GroupId;
                return PartialView("_EditPoints", vm);
            }
            ViewBag.SeasonId = vm.SeasonId;
            TempData["LeagueId"] = vm.LeagueId;
            return PartialView("_Edit", vm);
        }

        [HttpPost]
        public ActionResult EditPoints(GroupsForm vm)
        {
            for (var i = 0; i < vm.IdTeams.Count(); i++)
            {
                if (vm.IdTeams[i] == null || TempData["GroupId"] == null)
                    continue;
                var team = teamRepo.GetGroupTeam((int)TempData["GroupId"], (int)vm.IdTeams[i]);
                if (team != null)
                    team.Points = vm.Points[i];
            }
            teamRepo.Save();
            TempData["LeagueId"] = vm.LeagueId;
            return PartialView("_Edit", vm);
        }


    }
}

LogLig-Main/CmsApp/Controllers/SchedulesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using System.IO;
using AppModel;
using CmsApp.Models;
using DataService;
using ClosedXML.Excel;
using System.Web;
using System.Globalization;
using System.Threading;
using System.Net;
using DataService.DTO;

namespace CmsApp.Controllers
{
    public class SchedulesController : AdminController
    {
        // GET: Schedules
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult List(int id, bool desOrder, bool isChronological = false,
            int dateFilterType = Schedules.DateFilterPeriod.BeginningOfMonth,
            DateTime? dateFrom = null, DateTime? dateTo = null, int? inpSeasonId = null)
        {
            var res = new Schedules();
            res.dateFilterType = dateFilterType;
            res.dateFrom = dateFrom ?? Schedules.FirstDayOfMonth;
            res.dateTo = dateTo ?? Schedules.Tomorrow;
            var league = leagueRepo.GetById(id);
            var cond = new GamesRepo.GameFilterConditions
            {
                seasonId = inpSeasonId ?? leagueRepo.GetById(id).SeasonId ?? seasonsRepository.GetLastSeason().Id,
                auditoriums = new List<AuditoriumShort>(),
                leagues = new List<LeagueShort>
                {
                    new LeagueShort
                    {
                        Id = id,
                        UnionId = league.UnionId,
                        Check = true,
                        Name = league.Name
                    }
                }
            };
            if (dateFilterType == Schedules.DateFilterPeriod.BeginningOfMonth && isChronological)
            {
                cond.dateFrom = Schedules.FirstDayOfMonth;
                cond.dateTo = null;
            }
            else if (dateFilterType == Schedules.DateFilterPeriod.Ranged && isChronological)
            {
                cond.dateFrom = dateFrom;
                cond.dateTo = dateTo;
            }
            else
            {
                cond.dateFrom = null;
                cond.dateTo = null;
            }
            res.Games = gamesRepo.GetCyclesByFilterConditions(cond,
                User.IsInAnyRole(AppRole.Admins, AppRole.Editors, AppRole.Workers), false)
                .Select(gc => new GamesInLeague(gc)
                {
                    LeagueId = gc.Stage.LeagueId,
                    LeagueName = gc.Stage.League.Name,
                    IsPublished = gc.IsPublished,
                }).ToList();

            if (desOrder)
                res.Games = res.Games.OrderByDescending(x => x.Stage.Number).ToList();

            string alias = string.Empty;

            Session["desOrder"] = desOrder;
            var unionId = league.UnionId;
            if (unionId.HasValue)
            {
                res.Referees = usersRepo.GetUnionAndLeageReferees(unionId.Value, id).ToArray();

                res.Auditoriums = auditoriumsRepo.GetByUnionAndSeason(unionId.Value, cond.seasonId)
                    .Select(au => new AuditoriumShort
                    {
                        Id = au.AuditoriumId,
                        Name = au.Name
                    }).ToArray();

                alias = league.Union.Section?.Alias;
            }

            res.Leagues = cond.leagues.ToArray();
            res.SeasonId = cond.seasonId;
            res.UnionId = unionId;
            res.teamsByGroups = teamRepo.GetGroupTeamsBySeasonAndLeagues(cond.seasonId, new int[] { league.LeagueId });
            Session["isChronological"] = isChronological;

            switch (alias)
            {
                case GamesAlias.WaterPolo:
                case GamesAlias.BasketBall:
                    if (isChronological)
                    {
                        return PartialView("BasketBallWaterPolo/_ChronologicalList", res);
                    }
                    else
                    {
                        return PartialView("BasketBallWaterPolo/_List", res);
                    }

                default:
                    if (isChronological)
                    {
                        return PartialView("_ChronologicalList", res);
                    }
                    else
                    {
                        return PartialView("_List", res);
                    }

            }



        }

        [HttpPost]
        public ActionResult PublishAllLeagueGamesCycles(int seasonId, int leagueId, bool isPublished)
        {
            try
            {
                IEnumerable<GamesCycle> games = gamesRepo.GetGroupsCycles(leagueId, seasonId).ToList();
                games.ForEach(g => g.IsPublished = isPublished);

                gamesRepo.Update(games);

                return new HttpStatusCodeResult(200);
            }
            catch (Exception)
            {
                return new HttpStatusCodeResult(500);
            }
        }

        [HttpPost]
        public ActionResult PublishGamesCyclesByCycleNumber(int seasonId, int leagueId, int stageId, int cycleNum, bool isPublished)
        {
            try
            {
                var games = gamesRepo.GetGroupsCycles(leagueId, seasonId)
                                      .Where(g => g.CycleNum == cycleNum && g.StageId == stageId)
                                      .ToList();
                games.ForEach(g => g.IsPublished = isPublished);

                gamesRepo.Update(games);

                return new HttpStatusCodeResult(200);
            }
            catch (Exception)
            {
                return new HttpStatusCodeResult(500);
            }
        }

        [HttpPost]
        public ActionResult PublishGamesCycle(int gameCycleId, bool isPublished)
        {
            try
            {
                GamesCycle gameCycle = gamesRepo.GetGameCycleById(gameCycleId);
                gameCycle.IsPublished = isPublished;

                gamesRepo.Update(gameCycle);

                return new HttpStatusCodeResult(HttpStatusCode.OK);
            }
            catch (Exception e)
            {
                return new HttpStatusCodeResult(HttpStatusCode.InternalServerError, e.ToString());
            }
        }

        public ActionResult TeamList(int id, int seasonId)
        {
            var model = new TeamSchedules();
            model.TeamId = id;
            model.SeasonId = id;
            model.Clubs = clubsRepo.GetByTeamAnsSeason(id, seasonId).Where(c => c.IsSectionClub.Value).ToList();
            model.LeaguesWithCycles = teamRepo.GetTeamGames(id, seasonId).ToList();
            string alias = secRepo.GetSectionByTeamId(id).Alias;

            switch (alias)
            {
                case GamesAlias.BasketBall:
                case GamesAlias.WaterPolo:
                    return PartialView("BasketBallWaterPolo/_TeamList", model);

                default:
                    return PartialView("_TeamList", model);

            }
        }

        public ActionResult ExportToExcelUnion(List<int> leaguesId, int sortType, int seasonId)
        {
            leaguesId = (List<int>)Session["LeaguesIds"];
            var xlsService = new ExcelGameService();
            bool isBasketBallOrWaterPolo = false;
            var games = new List<ExcelGameDto>();
            foreach (var leagueId in leaguesId)
            {
                games.AddRange(xlsService.GetLeagueGames(leagueId, seasonId));
            }

            if (games?.Count() > 0)
            {
                isBasketBallOrWaterPolo = gamesRepo.IsBasketBallOrWaterPoloGameCycle(games[0].GameId);
            }

            if (sortType == 1)
                games = games.OrderBy(x => x.Date).ToList();
            if (sortType == 2)
                games = games.OrderBy(x => x.Auditorium).ToList();

            return ToExcel(games, isBasketBallOrWaterPolo);
        }

        public ActionResult ExportToExcel(int? leagueId, int? teamId, int? currentLeagueId, int? seasonId,
            int dateFilterType = Schedules.DateFilterPeriod.All,
            DateTime? dateFrom = null, DateTime? dateTo = null)
        {
            var xlsService = new ExcelGameService();
            bool userIsEditor = User.IsInAnyRole(AppRole.Admins, AppRole.Editors, AppRole.Workers);
            var games = new List<ExcelGameDto>();
            bool isBasketBallOrWaterPolo = false;
            if (leagueId.HasValue)
            {
                isBasketBallOrWaterPolo = leagueRepo.IsBasketBallOrWaterPoloLeague(leagueId.Value);
                switch (dateFilterType)
                {
                    case Schedules.DateFilterPeriod.BeginningOfMonth:
                        games = xlsService.GetLeagueGames(leagueId.Value, userIsEditor, Schedules.FirstDayOfMonth, null).ToList();
                        break;
                    case Schedules.DateFilterPeriod.Ranged:
                        games = xlsService.GetLeagueGames(leagueId.Value, userIsEditor, dateFrom, dateTo).ToList();
                        break;
                    default:
                        games = xlsService.GetLeagueGames(leagueId.Value, userIsEditor, null, null).ToList();
                        break;
                }
            }
            else if (teamId.HasValue)
            {
                if (!seasonId.HasValue)
                {
                    seasonId = teamRepo.GetSeasonIdByTeamId(teamId.Value, DateTime.Now);
                }
                isBasketBallOrWaterPolo = seasonsRepository.IsBasketBallOrWaterPoloSeason(seasonId.Value);
                if (currentLeagueId.HasValue)
                {
                    games = xlsService.GetTeamGames(teamId.Value, currentLeagueId.Value, seasonId).ToList();
                }
                else
                {
                    games = xlsService.GetTeamGames(teamId.Value, seasonId).ToList();
                }
            }

LogLig-Main/CmsApp/Views/Schedules/_AddNewForm.cshtml
@model GameCycleFormFull

<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only"></span></button>
    <h4 class="modal-title">@Messages.AddGameToStage @Model.StageNum @Messages.Cycle @(Model.CycleNum + 1)</h4>
</div>

@using (Ajax.BeginForm("AddNew", null,
                new AjaxOptions { UpdateTargetId = "schedules", OnComplete = "$('#addsycle').modal('hide')" },
                new { id = "newgameform" }))
{
<div class="modal-body">
    <div class="row">
        <div class="form-group col-sm-6">
            <label class="control-label">@Messages.Date:</label>
            <input type='text' name='@nameof(Model.StartDate)' 
                   value='@Model.StartDate.ToString("dd/MM/yyyy HH:mm")' 
                   class="form-control frm-date required" />
            @*@Html.TextBoxFor(m => m.StartDate, new { @class = "form-control frm-date" })*@
            @Html.ValidationMessageFor(m => m.StartDate)
        </div>
        <div class="form-group col-sm-6">
            <label class="control-label">@Messages.Group:</label>
            @Html.DropDownListFor(m => m.GroupeId, Model.Groups, new { @class = "form-control" })
            @Html.ValidationMessageFor(m => m.GroupeId)
        </div>
    </div>
    <div class="row">
        <div class="form-group col-sm-6">
            <label class="control-label">@Messages.Auditorium:</label>
            @Html.DropDownListFor(m => m.AuditoriumId, Model.Auditoriums, new { @class = "form-control" })
            @Html.ValidationMessageFor(m => m.AuditoriumId)
        </div>
        <div class="form-group col-sm-6">
            <label class="control-label">@Messages.Referee:</label>
            @Html.DropDownListFor(m => m.RefereeId, Model.Referees, new { @class = "form-control" })
            @Html.ValidationMessageFor(m => m.RefereeId)
        </div>
    </div>
    <div class="row" id="groupteams_pl">
    </div>
</div>
<div class="modal-footer">
    <button type="button" class="btn btn-default" data-dismiss="modal">@Messages.Close</button>
    <button id="savebtn" class="btn btn-primary">@Messages.Save</button>
</div>
    @Html.HiddenFor(m => m.StageId)
    @Html.HiddenFor(m => m.CycleNum)
    @Html.HiddenFor(m => m.LeagueId)
}

<script>
    $(function () {
        $('#newgameform').validateBootstrap(true);

        var frm = $('#newgameform');

        function setTeamsDDL() {
            var groupId = $("#GroupeId", frm).val();
            $('#groupteams_pl', frm).load('@Url.Action("GoupTeams")' + '/' + groupId);
        }

        $('#GroupeId', frm).change(function () {
            setTeamsDDL();
        });

        $('#savebtn', frm).click(function () {

            $('#teamerr', frm).hide();

            var homeTeamId = $("#HomeTeamId", frm).val();
            var guestTeamId = $("#GuestTeamId", frm).val();
            if (homeTeamId == guestTeamId) {
                $('#teamerr', frm).show();
                return false;
            }
        });
        setTeamsDDL();
        cmn.initDateTimePickers();
    });
</script>

LogLig-Main/CmsApp/Views/Schedules/_Groups.cshtml
@model IEnumerable<AppModel.Group>

<div class="row offset-2">
    <div class="col-sm-6">
        <a href="@Url.Action("Create", "Stages", new { id = ViewBag.LeagueId, seasonId = ViewBag.SeasonId })"
           class="btn btn-primary"
           data-ajax-update="#stages"
           data-ajax-method="POST"
           data-ajax-begin="this.style.visibility='hidden'"
           data-ajax-success="this.style.visibility='visible'"
           data-ajax="true">@Messages.AddStage</a>

    </div>
</div>


<div class="row offset-2">
    <div id="stages" class="col-sm-6">
        @Html.Action("Index", "Stages", new {seasonId = ViewBag.SeasonId})
    </div>
</div>

<div class="row">
    <div id="groupslist" class="col-sm-12">
        @Html.Action("Index", "Groups", new {seasonId = ViewBag.SeasonId})
    </div>
</div>

<div class="modal fade" id="groupsedit" tabindex="-1" role="dialog">
    <div class="modal-dialog">
        <div class="modal-content"></div>
    </div>
</div>
<script>
    function activateTab(tab) {
        $('.nav-tabs a[href="#' + tab + '"]').tab('show');
    };
</script>

LogLig-Main/CmsApp/Views/Schedules/_TeamList.cshtml
@model TeamSchedules

@if (Model.LeaguesWithCycles.Count > 0)
{
    var firstLeagueId = Model.LeaguesWithCycles[0].Key.LeagueId;
    <div>
        <a class="btn btn-info" href="@Url.Action("ExportToExcel", "Schedules", new { teamId = Model.TeamId, currentLeagueId = firstLeagueId })">
            <i href="#" class="glyphicon glyphicon-open"></i> @Messages.ExportToExcel
        </a>

        <a href="@GlobVars.SiteUrl/LeagueTable/TeamSchedules/@Model.TeamId?leagueId=@firstLeagueId&seasonId=@Model.SeasonId" target="_blank" class="btn btn-info">@Messages.ExternalLink</a>

        <a href="#" id="team_print" class="btn btn-info">
            <i class="glyphicon glyphicon-print"></i>&nbsp @Messages.Print
        </a>
        @using (Html.BeginForm("Import", "Teams", FormMethod.Post, new { teamId = Model.TeamId, currentLeagueId = firstLeagueId, enctype = "multipart/form-data" }))
        {
            <input type="hidden" value="@Model.TeamId" name="TeamId" />
            <input type="hidden" value="@Model.SeasonId" name="SeasonId" />
            <input type="hidden" value="@firstLeagueId" name="CurrentLeagueId" />
            <input type="file" id="file-import-from-excel" name="ImportFile" style="display: none" />
        }
    </div>
}

@foreach (var club in Model.Clubs)
{
    <div>
        @Html.Label(club.Name)
        @Html.Action("GamesUrl", "Games", new { clubId = club.ClubId, teamId = Model.TeamId, seasonId = Model.SeasonId })
    </div>
}

@foreach (var league in Model.LeaguesWithCycles)
{
    <h2 class="team_tables">@league.Key.Name</h2>
    foreach (var stage in league)
    {
        <div class="team_tables">
            <h3>@Messages.Stage @stage.Key.Number</h3>
            <table class="table table-bordered">
                <thead>
                    <tr>
                        <th width="2%">@Messages.Status</th>
                        <th width="15%">@Messages.Group</th>
                        <th width="5%">@Messages.Cycle</th>
                        <th width="10%">@Messages.StartDate</th>
                        <th width="14%">@Messages.Auditorium</th>
                        <th width="10%">@Messages.Referee</th>
                        <th width="20%" class="text-center">@Messages.HomeTeam</th>
                        <th width="2%"></th>
                        <th width="2%"></th>
                        <th width="20%" class="text-center">@Messages.GuestTeam</th>
                    </tr>
                </thead>
                @foreach (var game in stage.OrderBy(g => g.StartDate))
                {
                    <tr>
                        <td class="res-stat remove_print">
                            @if (game.GameStatus == GameStatus.Started)
                            {
                                <span class="label label-success">@Messages.Started</span>
                            }
                            else if (game.GameStatus == GameStatus.Ended)
                            {
                                <span class="label label-danger">@Messages.Ended</span>
                            }
                            else
                            {
                                <span class="label label-default">@Messages.Waiting</span>
                            }
                        </td>
                        <td>@(game.Group != null ? game.Group.Name : "")</td>
                        <td>@Messages.Cycle @(game.CycleNum + 1)</td>
                        <td>@game.StartDate.ToString(Messages.DateFormat)</td>
                        <td>@(game.AuditoriumId.HasValue ? game.Auditorium.Name : "")</td>
                        <td class="remove_print">@(game.RefereeId.HasValue ? game.User.FullName : "")</td>
                        <td class="text-center">
                            @if (game.HomeTeam != null)
                            {
                                var homeTeam = game.HomeTeam.TeamsDetails.FirstOrDefault(x => x.SeasonId == Model.SeasonId);
                                if (homeTeam != null)
                                {
                                    <label>@homeTeam.TeamName</label>
                                }
                                else
                                {
                                    <label>@game.HomeTeam.Title</label>
                                }
                            }
                            else
                            {
                                @("--")
                            }
                        </td>
                        <td class="text-center">@game.HomeTeamScore</td>
                        <td class="text-center">@game.GuestTeamScore</td>
                        <td class="text-center">
                            @if (game.GuestTeam != null)
                            {
                                var guestTeam = game.GuestTeam.TeamsDetails.FirstOrDefault(x => x.SeasonId == Model.SeasonId);
                                if (guestTeam != null)
                                {
                                    <label>@guestTeam.TeamName</label>
                                }
                                else
                                {
                                    <label>@game.GuestTeam.Title</label>
                                }
                            }
                            else
                            {
                                @("--")
                            }
                        </td>
                    </tr>
                }
            </table>
        </div>
    }
}

<script>
    $('#team_print').click(function () {
        var el = $('.team_tables');
        if (el.length > 0) {
            teamPrint(el);
        }
    });

    function teamPrint(element) {
        var wnd = window.open('', 'Game schedules', 'height=600, width=600');
        wnd.document.write('<html><head><title>Game schedules</title>');
        //if need to add styles
        wnd.document.write('<link rel="stylesheet" href="/content/css/style.css" type="text/css" media="print" />');
        wnd.document.write('<link rel="stylesheet" href="/content/css/bootstrap.css" type="text/css" />');
        wnd.document.write('<link rel="stylesheet" href="/Content/site.css" type="text/css" />');

        wnd.document.write('<body>');
        $.each($(element), function (k, e) {
            if (k === 0) {
                wnd.document.write($(e).html());
                wnd.document.write('<hr/>');
            } else {
                $(e).find('thead').remove();
                wnd.document.write($(e).html());
                wnd.document.write('<hr/>');
            }
        });

        $(wnd.document).find('.remove_print').remove();
        $(wnd.document).find('th').remove();
        $(wnd.document).find('hr:last').remove();
        wnd.document.write('</body></html>');
        wnd.document.close();
        wnd.focus();
        setTimeout(function () {
            wnd.print();
        }, 1000);


    }
</script>

LogLig-Main/CmsApp/Views/Schedules/_TeamsView.cshtml
<div class="form-group col-sm-6">
    <label class="control-label">@Messages.HomeTeam:</label>
    @Html.DropDownList("HomeTeamId", ViewBag.TeamsList as IEnumerable<SelectListItem>,
            new { @class = "form-control" })
    <span id="teamerr" class="text-danger" style="display:none">@Messages.SelectOtherTeam</span>
</div>
<div class="form-group col-sm-6">
    <label class="control-label">@Messages.GuestTeam:</label>
    @Html.DropDownList("GuestTeamId", ViewBag.TeamsList as IEnumerable<SelectListItem>,
            new { @class = "form-control" })
</div>