LogLig-Main/CmsApp/Models/UnionForm.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.ComponentModel.DataAnnotations;
using System.Web.Mvc;
using AppModel;

namespace CmsApp.Models
{
  public class UnionDetailsForm
  {
    public int UnionId { get; set; }
    public int DocId { get; set; }

    [Required]
    [StringLength(50)]
    public string Name { get; set; }

    public string Logo { get; set; }
    public string PrimaryImage { get; set; }
    public bool IsHadicapEnabled { get; set; }

    [Required]
    [StringLength(250)]
    [DataType(DataType.MultilineText)]
    public string Description { get; set; }

    public string IndexImage { get; set; }
    public string IndexAbout { get; set; }
    public string ContactPhone { get; set; }
    public string Address { get; set; }
    public string Email { get; set; }
    public DateTime? CreateDate { get; set; }
    public string Terms { get; set; }

  }

  public class UnionsForm
  {
    public int SectionId { get; set; }

    [Required]
    public string Name { get; set; }

    public IEnumerable<Union> UnionsList { get; set; }

    public UnionsForm()
    {
      UnionsList = new List<Union>();
    }
  }

    public class EditUnionForm
    {
        public int UnionId { get; set; }
        public string UnionName { get; set; }
        public int SectionId { get; set; }
        public string SectionName { get; set; }
        public bool IsCatchBall { get; set; }
        public int? SeasonId { get; set; }

        public List<Season> Seasons { get; set; }
    }
}

LogLig-Main/CmsApp/Controllers/UnionsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using DataService;
using AppModel;
using CmsApp.Models;
using Omu.ValueInjecter;
using System.Web.UI.WebControls;
using System.IO;
using System.Web.UI;
using Resources;
using CmsApp.Helpers;
using MetascanHelper;

namespace CmsApp.Controllers
{
    public class UnionsController : AdminController
    {
        public ActionResult Edit(int id, int? seasonId = null)
        {
            var union = unionsRepo.GetById(id);

            if (union.IsArchive)
            {
                return RedirectToAction("NotFound", "Error");
            }

            if (User.IsInAnyRole(AppRole.Workers) && !AuthSvc.AuthorizeUnionByIdAndManagerId(id, AdminId))
            {
                return RedirectToAction("Index", "NotAuthorized");
            }

            var seasons = seasonsRepository.GetSeasonsByUnion(id).ToList();

            Session["CurrentUnionId"] = id;

            var model = new EditUnionForm
            {
                UnionId = id,
                UnionName = union.Name,
                SectionId = union.Section.SectionId,
                SectionName = union.Section.Name,
                IsCatchBall = union.Section.Alias == GamesAlias.NetBall,
                SeasonId = seasonId ?? GetUnionCurrentSeasonFromSession(),
                Seasons = seasons
            };            

            return View(model);
        }

        #region Info

        public ActionResult Details(int id)
        {
            var item = unionsRepo.GetById(id);

            var vm = new UnionDetailsForm();

            vm.InjectFrom(item);

            var doc = unionsRepo.GetTermsDoc(id);
            if (doc != null)
            {
                vm.DocId = doc.DocId;
            }

            if (TempData["ViewData"] != null)
            {
                ViewData = (ViewDataDictionary)TempData["ViewData"];
            }

            return PartialView("_Details", vm);
        }

        [HttpPost]
        public ActionResult Details(UnionDetailsForm frm)
        {
            var maxFileSize = GlobVars.MaxFileSize * 1000;
            var savePath = Server.MapPath(GlobVars.ContentPath + "/league/");
            var item = unionsRepo.GetById(frm.UnionId);

            UpdateModel(item);

            var imageFile = GetPostedFile("ImageFile");
            if (imageFile != null)
            {
                if (imageFile.ContentLength > maxFileSize)
                {
                    ModelState.AddModelError("ImageFile", Messages.FileSizeError);
                }
                else
                {
                    var newName = SaveFile(imageFile, "img");
                    if (newName == null)
                    {
                        ModelState.AddModelError("ImageFile", Messages.FileError);
                    }
                    else
                    {
                        if (!string.IsNullOrEmpty(item.PrimaryImage))
                            FileUtil.DeleteFile(savePath + item.PrimaryImage);

                        item.PrimaryImage = newName;
                    }
                }
            }

            var logoFile = GetPostedFile("LogoFile");
            if (logoFile != null)
            {
                if (logoFile.ContentLength > maxFileSize)
                {
                    ModelState.AddModelError("LogoFile", Messages.FileSizeError);
                }
                else
                {
                    var newName = SaveFile(logoFile, "logo");
                    if (newName == null)
                    {
                        ModelState.AddModelError("LogoFile", Messages.FileError);
                    }
                    else
                    {
                        if (!string.IsNullOrEmpty(item.Logo))
                            FileUtil.DeleteFile(savePath + item.Logo);

                        item.Logo = newName;
                    }
                }
            }

            var indexFile = GetPostedFile("IndexFile");
            if (indexFile != null)
            {
                if (indexFile.ContentLength > maxFileSize)
                {
                    ModelState.AddModelError("IndexFile", Messages.FileSizeError);
                }
                else
                {
                    var newName = SaveFile(indexFile, "img");
                    if (newName == null)
                    {
                        ModelState.AddModelError("IndexFile", Messages.FileError);
                    }
                    else
                    {
                        if (!string.IsNullOrEmpty(item.IndexImage))
                            FileUtil.DeleteFile(savePath + item.IndexImage);

                        item.IndexImage = newName;
                    }
                }
            }

            var docFile = GetPostedFile("DocFile");
            if (docFile != null)
            {
                if (docFile.ContentLength > maxFileSize)
                {
                    ModelState.AddModelError("DocFile", Messages.FileSizeError);
                }
                var isValid = SaveDocument(docFile, frm.UnionId);
                if (!isValid)
                {
                    ModelState.AddModelError("DocFile", Messages.FileError);
                }
            }

            if (ModelState.IsValid)
            {
                unionsRepo.Save();

                TempData["Saved"] = true;
            }
            else
            {
                TempData["ViewData"] = ViewData;
            }

            return RedirectToAction("Details", new { id = item.UnionId });
        }

        public ActionResult DeleteImage(int unionId, string image)
        {
            var item = unionsRepo.GetById(unionId);

            if (item == null || string.IsNullOrEmpty(image))
                return RedirectToAction("Edit", new { id = unionId });

            if (image == "PrimaryImage")
            {
                item.PrimaryImage = null;
            }

            if (image == "IndexImage")
            {
                item.IndexImage = null;
            }

            if (image == "Logo")
            {
                item.Logo = null;
            }
            unionsRepo.Save();

            return RedirectToAction("Edit", new { id = unionId });
        }

        public ActionResult ShowDoc(int id)
        {
            var doc = unionsRepo.GetDocById(id);

            Response.AddHeader("content-disposition", "inline;filename=" + doc.FileName + ".pdf");

            return this.File(doc.DocFile, "application/pdf");
        }

        [NonAction]
        private bool SaveDocument(HttpPostedFileBase file, int unionId)
        {
            string ext = Path.GetExtension(file.FileName).ToLower();

            if (ext != ".pdf")
            {
                return false;
            }

            var doc = unionsRepo.GetTermsDoc(unionId);
            if (doc == null)
            {
                doc = new UnionsDoc { UnionId = unionId };
                unionsRepo.CreateDoc(doc);
            }

            doc.FileName = file.FileName;

            byte[] docData;
            using (var reader = new BinaryReader(file.InputStream))
            {
                docData = reader.ReadBytes(file.ContentLength);
            }

            var req = new MetascanHelper.MetadataRequest(Guid.NewGuid().ToString(),
                file.FileName,
                docData,
                MetascanHelper.MetaScanAction.PostFileToMetaScan
                );

            string dataid = req.PostFileForScanning();
            MetaScanScanStatus metaScanStatus;
            req.CheckFileScan(dataid, out metaScanStatus);

            int tries = 3;
            while (metaScanStatus == MetaScanScanStatus.GeneralError && dataid != "" && tries > 0)
            {
                tries--;
                System.Threading.Thread.Sleep(2000);
                req.CheckFileScan(dataid, out metaScanStatus);
            }

            if (metaScanStatus == MetaScanScanStatus.Valid)
            {
                doc.DocFile = docData;
                unionsRepo.Save();
                return true;
            }

            return false;
        }

        [NonAction]
        private HttpPostedFileBase GetPostedFile(string name)
        {
            if (Request.Files[name] == null)
                return null;

            if (Request.Files[name].ContentLength == 0)
                return null;

            return Request.Files[name];
        }

        [NonAction]
        private string SaveFile(HttpPostedFileBase file, string name)
        {
            string ext = Path.GetExtension(file.FileName).ToLower();

            if (!GlobVars.ValidImages.Contains(ext))
                return null;

            string newName = name + "_" + AppFunc.GetUniqName() + ext;

            var savePath = Server.MapPath(GlobVars.ContentPath + "/union/");

            var di = new DirectoryInfo(savePath);
            if (!di.Exists)
                di.Create();

            byte[] imgData;
            using (var reader = new BinaryReader(file.InputStream))
            {
                imgData = reader.ReadBytes(file.ContentLength);
            }
            System.IO.File.WriteAllBytes(savePath + newName, imgData);
            return newName;
        }

        #endregion

        public ActionResult List(int id)
        {
            var vm = new UnionsForm { SectionId = id };

            if (User.IsInAnyRole(AppRole.Workers))
            {
                switch (usersRepo.GetTopLevelJob(base.AdminId))
                {
                    case JobRole.UnionManager:
                        vm.UnionsList = new UnionsRepo().GetByManagerId(base.AdminId);
                        break;
                    case JobRole.LeagueManager:
                        break;
                    case JobRole.TeamManager:
                        break;
                }

LogLig-Main/CmsApp/Views/Unions/Edit.cshtml
@model EditUnionForm
@Html.HiddenFor(m => m.SeasonId)

<div class="row">
    <div class="col-lg-10">
        <h3 class="sub-header">
            @{
                if (User.IsInAnyRole(AppRole.Admins, AppRole.Editors))
                {

                    <a href="@Url.Action("Edit", "Sections", new {id = Model.SectionId})">@Model.SectionName</a>
                }
                else
                {
                    @Model.SectionName
                }
            }
            &raquo; @Model.UnionName
        </h3>
    </div>
    <div class="col-lg-2">
        <div class="form-group" style="margin-top: 20px">
            @Html.DropDownListFor(m => m.SeasonId, new SelectList(Model.Seasons, "Id", "Name"), new { @class = "form-control", @id = "ddlSeasons" })
        </div>
    </div>
</div>

<ul class="nav nav-tabs" id="section_tabs" role="tablist">
    <li class="active"><a href="#details" data-toggle="tab">@Messages.Info</a></li>
    <li><a href="#clubs" data-toggle="tab">@Messages.ClubsInSection</a></li>
    <li><a href="#leagues" data-toggle="tab">@Messages.Leagues</a></li>
    @if (User.IsInAnyRole(AppRole.Admins, AppRole.Editors, AppRole.Workers))
    {
        <li><a href="#userstab" data-toggle="tab">@Messages.Workers</a></li>
        <li><a href="#auditoriums" data-toggle="tab">@Messages.Auditoriums</a></li>
        <li><a href="#schedules" data-toggle="tab">@Messages.GamesTable</a></li>
    }
    <li><a href="#eilatTournament" data-toggle="tab">
        @if (Model.IsCatchBall)
        {
            @Messages.EilatTournament
        }
        else
        {
           @Messages.Tournaments
        }
        
    </a></li>
    <li><a href="#seasons" data-toggle="tab">@Messages.Seasons</a></li>
    @if (User.IsInAnyRole(AppRole.Admins, AppRole.Editors, AppRole.Workers))
    {
        <li><a href="#notifications" data-toggle="tab">@Messages.Notifications</a></li>
    }
</ul>

<div id="groupmodal" class="tab-content row offset-3">

    <div class="tab-pane fade in active col-sm-9" id="details">
        @Html.Action("Details")
    </div>
    <div class="tab-pane fade col-sm-9" id="clubs">
        @Html.Action("ListByUnion", "Clubs", new { id = Model.UnionId, seasonId = Model.SeasonId })
    </div>

    <div class="tab-pane fade  col-sm-9" id="leagues">
        @Html.Action("Leagues", "Unions", new { id = Model.UnionId, seasonId = Model.SeasonId })
    </div>

    <div class="tab-pane fade col-sm-7 offset-2" id="userstab">
        <div id="workers_list">
            @Html.Action("WorkerList", "Jobs", new { id = Model.UnionId, logicalName = LogicaName.Union, seasonId = Model.SeasonId})
        </div>
    </div>

    <div class="tab-pane fade col-sm-7 offset-2" id="auditoriums">
        @Html.Action("List", "Auditoriums", new { unionId = Model.UnionId, seasonId = Model.SeasonId })
    </div>

    <div class="tab-pane fade col-sm-7 offset-2" id="eilatTournament">
        @Html.Action("EilatTournament", "Unions", new { unionId = Model.UnionId, seasonId = Model.SeasonId })
    </div>

    <div class="tab-pane fade" id="schedules">
        @Html.Action("List", "Sections", new
   {
       model = new Schedules
       {
          UnionId = Model.UnionId
       }, seasonId =  Model.SeasonId
   })
    </div>

    <div class="tab-pane fade col-sm-7 offset-2" id="seasons">
        @Html.Action("List", "Seasons", new { entityId = Model.UnionId, logicalName = LogicaName.Union })
    </div>

    <div class="tab-pane fade" id="notifications">
        @Html.Action("Add", "Notifications", new { entityId = Model.UnionId, logicalName = LogicaName.Union })
    </div>
</div>

<div class="modal fade" id="newleague" role="dialog">
    <div class="modal-dialog modal-sm">
        <div class="modal-content"></div>
    </div>
</div>

@section scripts
{
    <script>
        $('#ddlSeasons').change(function () {
            var seasonId = $(this).val();
            $.ajax({
                url: '/Admin/SetUnionCurrentSeason',
                type: 'POST',
                dataType: 'JSON',
                data: { seasonId },
                success: function () {

                }
            });
            window.location.href = '@Url.Action("Edit", new { id = Model.UnionId })?seasonId=' + seasonId;
        });
    </script>
}

LogLig-Main/CmsApp/Views/Unions/_ClubLeagues.cshtml
<form id="detailsform" method="post" data-targetid="Leagues" action="@Url.Action("Leagues")" autocomplete="off" enctype="multipart/form-data">
    @if (User.IsInAnyRole(AppRole.Admins, AppRole.Editors, AppRole.Workers))
    {
        <a href="@Url.Action("Create", "Leagues")"
           class="btn btn-primary"
           data-target="#newleague"
           data-toggle="modal">@Messages.CreateLeague</a>


        <a class="btn btn-info" href="@Url.Action("ExportReferees")">
            <i href="#" class="glyphicon glyphicon-open"></i> @Messages.ExportReferees
        </a>
    }
</form>

LogLig-Main/CmsApp/Views/Unions/_Leagues.cshtml
@model TournamentsPDF
@{
    int errId = TempData["ErrId"] != null ? (int)TempData["ErrId"] : 0;
}

<form id="detailsform" method="post" data-targetid="Leagues" action="@Url.Action("Leagues")" autocomplete="off" enctype="multipart/form-data">
    @if (User.IsInAnyRole(AppRole.Admins, AppRole.Editors, AppRole.Workers))
    {
        <a href="@Url.Action("Create", "Leagues", new {unionId = Model.UnionId, clubId = Model.ClubId, et = Model.Et, seasonId = Model.SeasonId})"
           class="btn btn-primary"
           data-target="#newleague"
           data-toggle="modal">
            @if (Model.Et == TournamentsPDF.EditType.TmntSectionClub || Model.Et == TournamentsPDF.EditType.TmntUnionClub)
            {
                @Messages.AddTournament
            }
            else if (Model.Et == TournamentsPDF.EditType.LgUnion)
            {
                @Messages.CreateLeague
            }
            else if (Model.Et == TournamentsPDF.EditType.TmntUnion)
            {
                @Messages.CreateTournament
            }
        </a>


        <a class="btn btn-info" href="@Url.Action("ExportReferees", new {id = Model.UnionId})">
            <i href="#" class="glyphicon glyphicon-open"></i> @Messages.ExportReferees
        </a>
    }
    @if (Model.Et == TournamentsPDF.EditType.TmntUnion)
    {
        if (User.IsInAnyRole(AppRole.Admins, AppRole.Editors, AppRole.Workers))
        {
            <p>
                @Html.HiddenFor(m => m.Pdf1)
                @Html.HiddenFor(m => m.Pdf2)
                @Html.HiddenFor(m => m.Pdf3)
                @Html.HiddenFor(m => m.Pdf4)
                @{
                    string pdf1Hidden = Model.Pdf1 == null ? "hidden" : "";
                    string pdf2Hidden = Model.Pdf2 == null ? "hidden" : "";
                    string pdf3Hidden = Model.Pdf3 == null ? "hidden" : "";
                    string pdf4Hidden = Model.Pdf4 == null ? "hidden" : "";
                }
                <div class="row">
                    <div class="col-sm-3">
                        <label for="PDF1_file" class="control-label">PDF1</label> (<span>2mb</span>)
                        <span id="Pdf1_anchor" @pdf1Hidden>
                            <a href="@Url.Action("ShowGlobalDoc", "Unions", new { name = Model.Pdf1 })" target="_blank">@Messages.ShowTerms</a>
                        </span>
                    </div>
                    <div class="col-sm-3">
                        <label for="PDF2_file" class="control-label">PDF2</label> (<span>2mb</span>)
                        <span id="Pdf2_anchor" @pdf2Hidden>
                            <a href="@Url.Action("ShowGlobalDoc", "Unions", new { name = Model.Pdf2 })" target="_blank">@Messages.ShowTerms</a>
                        </span>
                    </div>
                    <div class="col-sm-3">
                        <label for="PDF3_file" class="control-label">PDF3</label> (<span>2mb</span>)
                        <span id="Pdf3_anchor" @pdf3Hidden>
                            <a href="@Url.Action("ShowGlobalDoc", "Unions", new { name = Model.Pdf3 })" target="_blank">@Messages.ShowTerms</a>
                        </span>
                    </div>
                    <div class="col-sm-3">
                        <label for="PDF4_file" class="control-label">PDF4</label> (<span>2mb</span>)
                        <span id="Pdf4_anchor" @pdf4Hidden>
                            <a href="@Url.Action("ShowGlobalDoc", "Unions", new { name = Model.Pdf4 })" target="_blank">@Messages.ShowTerms</a>
                        </span>
                    </div>
                </div>
                <div class="row">
                    <div class="col-sm-3 form-group">
                        <span class="btn btn-default btn-file col-sm-8">
                            <span>@Messages.AddFile</span>
                            <input type="file" id="PDF1_file" name="PDF1_file" data-val="true" data-val-regex-pattern="^.*\.(pdf|PDF)$" data-val-regex="@string.Format(Messages.SelectValidFile, "PDF")" accept="application/pdf" />
                        </span>
                        <span title="Remove file" class="btn btn-default col-sm-4" onclick="javascript:clearFile(1)">
                            <i class="glyphicon glyphicon-remove"></i>
                        </span>
                        @Html.ValidationMessage("DocFile")
                    </div>
                    <div class="col-sm-3 form-group">
                        <span class="btn btn-default btn-file col-sm-8">
                            <span>@Messages.AddFile</span>
                            <input type="file" id="PDF2_file" name="PDF2_file" data-val="true" data-val-regex-pattern="^.*\.(pdf|PDF)$" data-val-regex="@string.Format(Messages.SelectValidFile, "PDF")" accept="application/pdf" />
                        </span>
                        <span title="Remove file" class="btn btn-default col-sm-4" onclick="javascript:clearFile(2)">
                            <i class="glyphicon glyphicon-remove"></i>
                        </span>
                        @Html.ValidationMessage("DocFile")
                    </div>
                    <div class="col-sm-3 form-group">
                        <span class="btn btn-default btn-file col-sm-8">
                            <span>@Messages.AddFile</span>
                            <input type="file" id="PDF3_file" name="PDF3_file" data-val="true" data-val-regex-pattern="^.*\.(pdf|PDF)$" data-val-regex="@string.Format(Messages.SelectValidFile, "PDF")" accept="application/pdf" />
                        </span>
                        <span title="Remove file" class="btn btn-default col-sm-4" onclick="javascript:clearFile(3)">
                            <i class="glyphicon glyphicon-remove"></i>
                        </span>
                        @Html.ValidationMessage("DocFile")
                    </div>
                    <div class="col-sm-3 form-group">
                        <span class="btn btn-default btn-file col-sm-8">
                            <span>@Messages.AddFile</span>
                            <input type="file" id="PDF4_file" name="PDF4_file" data-val="true" data-val-regex-pattern="^.*\.(pdf|PDF)$" data-val-regex="@string.Format(Messages.SelectValidFile, "PDF")" accept="application/pdf" />
                        </span>
                        <span title="Remove file" class="btn btn-default col-sm-4" onclick="javascript:clearFile(4)">
                            <i class="glyphicon glyphicon-remove"></i>
                        </span>
                        @Html.ValidationMessage("DocFile")
                    </div>
                </div>
                @if (TempData["Saved"] != null)
                {
                <span class="text-success">@Messages.DataSavedSuccess</span>
                }
                <button class="btn btn-primary">@Messages.Save</button>
                <br>
            </p>
                        }
                    }

    <table class="table table-bordered offset-3">
        <thead>
            <tr>
                <th>@Messages.Name</th>
                <th>@Messages.Ages</th>
                <th>@Messages.Gender</th>
                <th></th>
                @if (User.IsInAnyRole(AppRole.Admins, AppRole.Editors, AppRole.Workers))
                {
                    <th></th>
                }
            </tr>
        </thead>
        <tbody id="sortable">
            @foreach (var m in Model.listLeagues)
            {
                @Html.HiddenFor(x => x.UnionId)
                <tr data-id="@m.LeagueId">
                    <td>
                        @m.Name
                        @if (errId == m.LeagueId)
                        {
                            <div class="text-danger offset-1">@Messages.DeleteTeamsFirst</div>
                        }
                    </td>
                    <td>@m.Age.Title</td>
                    <td>@LangHelper.GetGender(m.Gender.TitleMany)</td>
                    @if (User.IsInAnyRole(AppRole.Admins, AppRole.Editors, AppRole.Workers))
                    {
                        <td>
                            <a class="@AppCss.Edit" href="@Url.Action("Edit", "Leagues", new {id = m.LeagueId, seasonId = m.SeasonId})"></a>
                        </td>
                        <td>
                            <a href="@Url.Action("DeleteLeagues", new {id = m.LeagueId})" class="@AppCss.Delete"
                               data-ajax-confirm="@Messages.DeleteConfirm"
                               data-ajax-update="#leagues"
                               data-ajax="true"></a>
                        </td>
                    }
                </tr>

            }
        </tbody>
    </table>

</form>

<script>
    function activateTab(tab) {
        $('.nav-tabs a[href="#' + tab + '"]').tab('show');
    };

    function clearFile(num) {
        $('#Pdf' + num).val(null);
        $('#Pdf' + num + '_anchor').hide();
    }

    // Return a helper with preserved width of cells
    var fixHelper = function (e, ui) {
        ui.children().each(function () {
            $(this).width($(this).width());
        });
        return ui;
    };

    $(function () {
        $('#sortable').sortable({
            items: "tr",
            cursor: 'move',
            helper: fixHelper,
            update: function (event, ui) {

                var ids = [];
                var childs = event.target.children;

                $.each(childs, function (key, elem) {
                    var id = $(elem).attr('data-id');
                    ids.push(id);
                });

                //console.log(array);
                var postData = {
                    unionId: '@Model.UnionId',
                    ids: ids,
                    seasonId: $('#ddlSeasons').val()
                }
                $.ajax({
                    url: '@Url.Action("ChangeOrder", "Unions")',
                    data: postData,
                    type: 'POST',
                    dataType: 'json',
                    success: function (result) {
                        if (result.Success) {
                            console.log('Order updated');
                        } else {
                            console.log('Order not updated');
                        }
                    }
                })
            }
        }).disableSelection();
    });
</script>

LogLig-Main/CmsApp/Views/Unions/_List.cshtml
@model UnionsForm
@{
    int savedId = TempData["SavedId"] != null ? (int)TempData["SavedId"] : 0;
    int errId = TempData["ErrId"] != null ? (int)TempData["ErrId"] : 0;
}
<table class="table table-bordered">
    <tbody>
        @foreach (var m in Model.UnionsList)
        {
            string frmid = "unionsform" + m.UnionId;
            if (User.IsInAnyRole(AppRole.Admins, AppRole.Editors))
            {
                <tr>
                    <td>
                        @using (Ajax.BeginForm("Update", "Unions", new AjaxOptions { UpdateTargetId = "unions" }, new { id = frmid }))
                        {
                            <span class="form-group">
                                <input type="text" name="Name" value="@m.Name" form="@frmid" class="form-control required" maxlength="50" />
                                @Html.ValidationMessage("Name")
                            </span>
                            if (errId == m.UnionId)
                            {
                                <div class="text-danger">@Messages.DeleteLeaguesFirst</div>
                            }
                            <input type="hidden" name="UnionId" form="@frmid" value="@m.UnionId" />
                        }
                    </td>
                    <td>
                        <button class="@AppCss.Save @(savedId == m.UnionId ? "btn-success" : null) btn" form="@frmid"></button>
                    </td>
                    <td>
                        <a class="btn btn-primary" href="@Url.Action("Edit", "Unions", new { id = m.UnionId })">@Messages.Details</a>
                    </td>
                    <td>
                        <a href="@Url.Action("Delete", new { id = m.UnionId })" class="@AppCss.Delete"
                           data-ajax-confirm="@Messages.DeleteConfirm"
                           data-ajax-update="#unions"
                           data-ajax="true"></a>
                    </td>
                </tr>
            }
            else
            {
                <tr>
                    <td>
                        @m.Name
                    </td>
                    <td>
                        <a class="btn btn-primary" href="@Url.Action("Edit", "Unions", new { id = m.UnionId })">@Messages.Details</a>
                    </td>
                </tr>
            }
        }
    </tbody>
    @if (User.IsInAnyRole(AppRole.Admins, AppRole.Editors))
    {
        <tfoot>
            <tr>
                <td>
                    @using (Ajax.BeginForm("Save", "Unions", new AjaxOptions { UpdateTargetId = "unions" }, new { id = "unionsform" }))
                    {
                        <span class="form-group">
                            @Html.TextBoxFor(m => m.Name, new { @class = "form-control", placeholder = Messages.AddNew, form = "unionsform", maxlength = 50 })
                            @Html.ValidationMessageFor(m => m.Name)
                        </span>
                        @Html.HiddenFor(m => m.SectionId, new { form = "unionsform" })
                    }
                </td>
                <td>
                    <button class="btn btn-primary" form="unionsform">@Messages.Save</button>
                </td>
                <td colspan="2"></td>
            </tr>
        </tfoot>
    }
</table>

<script>
    $('#unionsform').validateBootstrap(true);
</script>